//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GppApp.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GppAppEntities : DbContext
    {
        public GppAppEntities()
            : base("name=GppAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ProjectItems> ProjectItems { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<UserDetails> UserDetails { get; set; }
        public virtual DbSet<ItemImages> ItemImages { get; set; }
        public virtual DbSet<ProjectsHistory> ProjectsHistory { get; set; }
        public virtual DbSet<ProjectItemsHistory> ProjectItemsHistory { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<UserTypes> UserTypes { get; set; }
    }
}
