//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GppApp.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectItems
    {
        public int Id { get; set; }
        public string ProjectId { get; set; }
        public string ItemDescription { get; set; }
        public string ProjectNotes { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> SysDate { get; set; }
    }
}
